elo/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
import ladder.views
import elo.views
from django.urls import include, path

app_name = 'elo'
urlpatterns = [
    url(r'^$',          ladder.views.index,                             name='index'),
    url(r'^l/',         include(('ladder.urls', 'ladder'),              namespace = 'ladder')),
    url(r'^u/',         include(('usercontrol.urls', 'usercontrol'),    namespace = 'user')),
    url(r'^logout/$',   elo.views.logout_view,                          name='logout'),
    url(r'^admin/',     admin.site.urls,                                name='admin'),
]

ladder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import ladder.views

admin.autodiscover()

urlpatterns = [
    url(r'^create/$',       ladder.views.create_ladder,     name='create'),
    url(r'^add_game/$',     ladder.views.add_game,          name='add_game'),

    url(r'^(?P<ladder_slug>[-\w]+)/', include([
        url(r'^$',                              ladder.views.index,                 name='detail'),
        url(r'^matches/$',                      ladder.views.match_list,            name='match_list'),
        url(r'^matches/(?P<match_id>\d+)/$',    ladder.views.match_detail,          name='match_detail'),
        url(r'^join/$',                         ladder.views.join_ladder,           name='join'),
        url(r'^leave/$',                        ladder.views.leave_ladder,          name='leave'),
        url(r'^edit/$',                         ladder.views.update_ladder,         name='update_ladder'),
        url(r'^challenge/$',                    ladder.views.issue_challenge,       name='issue_challenge'),
    ])),
]

usercontrol/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import usercontrol.views

admin.autodiscover()

urlpatterns = [
    url(r'^profile/(?P<username>[-\w]+)$', usercontrol.views.profile,             name = 'profile'),
    url(r'^profile/(?P<username>[-\w]+)/matches$', usercontrol.views.match_list,  name = 'match_list'),
    url(r'^messages/$',                     usercontrol.views.message_list,       name = 'message_list'),
    url(r'^messages/challenges/$',          usercontrol.views.message_challenges, name = 'message_challenges'),
    url(r'^messages/matches/$',             usercontrol.views.message_matches,    name = 'message_matches'),
    url(r'^messages/(?P<message>\d+)/$',    usercontrol.views.message_detail),
    url(r'^messages/send$',                 usercontrol.views.message_send),
]

ladder/models.py
# -*- coding: utf-8 -*-
import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Q
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.signals import post_save, post_delete
from django.template.defaultfilters import slugify
from django.urls.base import reverse
from django.utils.timezone import utc
from ladder.exceptions import ParticipantBusy, PlayerNotRanked, ChallengeeOutOfRange, ChallengeeIsChallenger

def _can_challenge_user( challenger, challengee, ladder ) :
    """ This function validates a challenge before it is saved """
    # Make sure the challengee is actually unique
    if challenger == challengee :
        raise ChallengeeIsChallenger( "you cannot challenge yourself" )

    # Attempt to get the ranks of the participants
    try :
        challenger_rank = Rank.objects.get( ladder = ladder, player = challenger )
        challengee_rank = Rank.objects.get( ladder = ladder, player = challengee )
    except ObjectDoesNotExist :
        # Rank couldn't be retrieved, but both players must be ranked
        raise PlayerNotRanked( "either the challenger {} or challengee {} is not ranked on the ladder".format( challenger, challengee, ladder ), ladder )

    # Make sure the participants aren't already busy with another challenge
    active_ladder_challenges = Challenge.objects.filter( ladder = ladder ).filter( Q(accepted = Challenge.STATUS_ACCEPTED) | Q(accepted = Challenge.STATUS_NOT_ACCEPTED) )
    active_ladder_challenges = active_ladder_challenges.exclude( challenger = challenger, challengee = challengee ) # Exclude ourselves
    if      active_ladder_challenges.filter( Q( challenger = challenger ) | Q( challengee = challenger ) ) :
        raise ParticipantBusy( "cannot issue a new challenge with open challenges already", challenger )
    elif    active_ladder_challenges.filter( Q( challenger = challengee ) | Q( challengee = challengee ) ) :
        raise ParticipantBusy( "cannot issue a challenge to a player already busy with another challenge", challengee )

    # Find the difference between ranks
    rankdiff = challenger_rank.rank - challengee_rank.rank

    # Make sure the ranks are different
    if rankdiff == 0 :
        raise ChallengeeOutOfRange( "challengee and challenger are equally ranked at {}".format( challenger_rank.rank ), rankdiff )

    # Check that the target of the challenge is within the ladder's specified range
    if challenger_rank.arrow == Rank.ARROW_UP :
        if rankdiff < 0 or rankdiff > int( ladder.up_arrow ) :
            raise ChallengeeOutOfRange( "challengee is ranked {}, which can't be challenged from {}".format( challengee_rank.rank, challenger_rank.rank ), rankdiff )
    elif challenger_rank.arrow == Rank.ARROW_DOWN :
        if rankdiff > 0 or -rankdiff > int( ladder.down_arrow ) :
            raise ChallengeeOutOfRange( "challengee is ranked {}, which can't be challenged from {}".format( challengee_rank.rank, challenger_rank.rank ), rankdiff )
    else :
        # Somehow the challenger has an invalid arrow
        raise ValueError( "challenger arrow is invalid", challenger_rank.arrow )

    return True

def _get_user_challenges(user, ladder = None, statuses = None):
    """Get all the challenges from a specified user (challenger or challengee). When no ladder statuses passed along, returns all challenges.
        user    = User object
        ladder  = Ladder object (optional)
        statuses = Tuple of challenge statuses (see ladder views)
    """

    # Grab the challenges from a user without filters
    open_challenges = Challenge.objects.filter((Q(challengee = user) | Q(challenger = user)))

    # Narrow it down to a single ladder if provided.
    if ladder is not None:
        open_challenges = open_challenges.filter( ladder = ladder )

    # Narrow it down to statuses requested
    if statuses is not None:
        for status in statuses:
            open_challenges = open_challenges.filter( accepted = status )

    return open_challenges

class Game(models.Model):
    name    = models.CharField(max_length=50, unique=True)
    abv     = models.CharField(max_length=10, unique=True)
    slug    = models.CharField(max_length=50, blank=True, editable=False)
    icon    = models.ImageField(upload_to='img/games', blank=True)

    def save(self, force_insert=False, force_update=False, using=None):
        self.slug = slugify(self.name)
        super(Game, self).save()

    def __str__(self):
        return self.name

class Ladder(models.Model):
    PRIVACY_OPEN     = u'0'
    PRIVACY_UNLISTED = u'1'
    PRIVACY_PRIVATE  = u'2'

    PRIVACY_LEVELS = (
        (PRIVACY_OPEN,      u'Open'),
        (PRIVACY_UNLISTED,  u'Unlisted'),
        (PRIVACY_PRIVATE,   u'Private'),
    )

    WEEKDAYS = (
        (u'0', u'Sunday'),
        (u'1', u'Monday'),
        (u'2', u'Tuesday'),
        (u'3', u'Wednesday'),
        (u'4', u'Thursday'),
        (u'5', u'Friday'),
        (u'6', u'Saturday'),
    )

    def ranked_players(self):
        """Gets number of players on ladder."""
        return Rank.objects.filter( ladder = self ).count()

    def save(self, force_insert=False, force_update=False, using=None, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Ladder, self).save(*args, **kwargs)

    def latest_match(self):
        matches = Match.objects.filter(ladder_id=self.id).order_by('-date_challenged').first()
        if not matches :
            return "Never"
        return matches.date_challenged

    def is_user_ranked( self, user ) :
        return user.rank_set.get( ladder = self ) != None
    
    def __str__(self):
        return "{0} ({1})".format(self.name, self.game.name)

    name                = models.CharField(max_length=50, blank=False, unique=True)
    slug                = models.CharField(max_length=60, blank=True, editable=False)

    description         = models.TextField(blank=True)

    owner               = models.ForeignKey('auth.User', null=True, blank=True, on_delete=SET_NULL)
    game                = models.ForeignKey(Game, null=True, blank=True, on_delete=SET_NULL)
    players             = property(ranked_players)
    latest_activity     = property(latest_match)
    max_players         = models.IntegerField(default='0', validators=[MinValueValidator(0),])
    privacy             = models.CharField(max_length=2, choices=PRIVACY_LEVELS, blank=False, default=PRIVACY_OPEN)
    signups             = models.BooleanField(blank=False, default=True)
    created             = models.DateTimeField("Ladder Created", blank=False, auto_now_add=True)
    end_date            = models.DateTimeField("Ladder Closes", blank=True, null=True)
    up_arrow            = models.IntegerField("Up arrow range", default='2', validators=[MinValueValidator(0),])
    down_arrow          = models.IntegerField("Down arrow range", default='4', validators=[MinValueValidator(0),])
    weekly_reset        = models.CharField(max_length=2, choices=WEEKDAYS, blank=True, null=True)
    challenge_cooldown  = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(0),])
    response_timeout    = models.IntegerField(blank=True, default='3', validators=[MinValueValidator(0),])


class Rank(models.Model):
    ARROW_UP    = u'0'
    ARROW_DOWN  = u'1'

    ARROW_ICONS = (
        (ARROW_UP,   u"▲"),
        (ARROW_DOWN, u"▼"),
    )

    class Meta:
        verbose_name_plural = "Rankings"
        verbose_name        = "Rank"

    player  = models.ForeignKey('auth.User', null=False, blank=False, on_delete=CASCADE)
    rank    = models.IntegerField()
    arrow   = models.CharField(max_length=2, choices=ARROW_ICONS, default='0')
    ladder  = models.ForeignKey(Ladder, null=True, blank=False, on_delete=SET_NULL)

    def __str__(self):
        return u"{0} [{1}{2}]".format(self.player.userprofile.handle, self.rank, self.get_arrow_display())


class Challenge(models.Model):
    STATUS_NOT_ACCEPTED = u'0'
    STATUS_ACCEPTED     = u'1'
    STATUS_FORFEIT      = u'2'
    STATUS_POSTPONED    = u'3'
    STATUS_COMPLETED    = u'4'
    STATUS_CANCELLED    = u'5'

    CHALLENGE_RESPONSES = (
        (STATUS_NOT_ACCEPTED,  u'Not Accepted'),
        (STATUS_ACCEPTED,      u'Accepted'),
        (STATUS_FORFEIT,       u'Forfeit'),
        (STATUS_POSTPONED,     u'Postponed'),
        (STATUS_COMPLETED,     u'Completed'),
        (STATUS_CANCELLED,     u'Cancelled')
    )

    challenger  = models.ForeignKey('auth.User', related_name='challenge_challenger', null=True, blank=False, on_delete=SET_NULL)
    challengee  = models.ForeignKey('auth.User', related_name='challenge_challengee', null=True, blank=False, on_delete=SET_NULL)
    date_issued = models.DateTimeField()
    deadline    = models.DateTimeField('Challenge Expires', null=True, blank=True)
    accepted    = models.CharField(max_length=2, choices=CHALLENGE_RESPONSES, blank=False, default=0)
    ladder      = models.ForeignKey(Ladder, blank=True, null=True, on_delete=SET_NULL)
    note        = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{0} vs {1}".format(self.challenger, self.challengee)

    def accept(self):
        self.accepted = Challenge.STATUS_ACCEPTED

    def forfeit(self):
        self.accepted = Challenge.STATUS_FORFEIT

    def postpone(self):
        self.accepted = Challenge.STATUS_POSTPONED

    def complete(self):
        self.accepted = Challenge.STATUS_COMPLETED

    def cancel(self):
        self.accepted = Challenge.STATUS_CANCELLED
        self.delete()

    def save(self, *args, **kwargs):
        # Check that our challenge is actually valid
        _can_challenge_user( self.challenger, self.challengee, self.ladder )

        # Setup the deadline based on the ladder's timeout
        if not self.deadline :
            ladder = self.ladder

ladder/templates/add_game.html
{% extends "layout.html" %}

{% load static %}
{% block head %}{% endblock head %}


{% block content %}
<form action="{% url 'ladder:add_game' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock content %}

ladder/templates/challenge.html
{% extends "layout.html" %}

{% load static %}

{% block head %}{% endblock head %}

{% block content %}

<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

{% endblock content %}

ladder/templates/confirm_join.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}{% endblock head %}

{% block content %}

<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

Are you sure you want to join the ladder: <u>{{ ladder.name }}</u> playing <em>{{ ladder.game.name }}</em>?<br />
<br />
<strong>Leaving the ladder will result in penalty and lockout from that ladder!</strong> (not really, but maybe soon.)<br />
<br />
<form action="{% url 'ladder:join' ladder.slug %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Join" />
</form>

{% endblock content %}

ladder/templates/confirm_leave.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}{% endblock head %}

{% block content %}

<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

<p>Are you sure you want to leave the ladder: <u>{{ ladder.name }}</u>?</p>
{% if challenges %}
<p>CHALLENGES: You have {{ challenges }} open or pending challenges on this ladder. <a href="{% url 'user:message_challenges' %}">Show Challenges</a></p>
<br/>
{% endif %}
{% if matches %}
<p> You have an open match on this ladder! <a href="{% url 'user:message_matches' %}">Show Matches</a></p>
{% endif %}
<br />
<p><strong>Leaving this ladder CANNOT BE <u>UNDONE</u> and everyone ranked below you will be moved up a rank.</strong></p>
<br />
<form action="{% url 'ladder:leave' ladder.slug %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Leave" />
</form>

{% endblock content %}

ladder/templates/create_ladder.html
{% extends "layout.html" %}

{% load static %}
{% block head %}{% endblock head %}


{% block content %}
<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

<form action="{% url 'ladder:create' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <br />
    <input type="submit" value="Submit" />
    <br />
    <a href="{% url 'ladder:add_game' %}">+ Add a game</a>
</form>
{% endblock content %}

ladder/templates/create_update_ladder.html
{% extends "layout.html" %}

{% load staticfiles %}
{% block head %}{% endblock head %}


{% block content %}
<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

<form action="/create/" method="post">
    {% csrf_token %}
    {{ form }}
    <br />
    <input type="submit" value="Submit" />
    <br />
    <a href="/add_game/">+ Add a game</a>
</form>
{% endblock content %}

ladder/templates/ladder_home.html
{% extends "layout.html" %}

{% load static %}
{% load humanize %}

{% block head %}{% endblock head %}

{% block content %}
<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

<h2>Ladders:</h2>
<ul>
{% for ladder in ladder_list %}
<li><a href="{% url 'ladder:detail' ladder.slug %}">{{ ladder }}</a> ({{ ladder.game.abv }})</li>
{% endfor %}
<li><a href="{% url 'ladder:create' %}">+ Create a ladder</a></li>
</ul>

{% if your_challenges %}
<hr>
<h2>Your Challenges</h2>
<ul>
    {% for challenge in your_challenges %}
    <li>{{ challenge }}</li>  
    {% endfor %}
</ul>
{% endif %}

<hr>
<h2>Recent Matches:</h2>
<table>
<tr>
    <th>Date</th>
    <th colspan="2">Challenger</th>
    <td></td>
    <th colspan="2">Defender</th>
    <th>Ladder</th>
    <th>Winner</th>
</tr>
{% for match in match_list %}
{% if match.winner %}
<tr>
    <td><a href="{% url 'ladder:match_detail' match.ladder.slug match.id %}">{{ match.date_complete|naturaltime }}</a></td>
    <td><img src="{{ match.challenger.userprofile.avatar }}" /></td>
    <td><a href="{% url 'user:profile' match.challenger.username %}">{{ match.challenger.userprofile.handle }}</a></td>
    <td><strong>vs</strong></td>
    <td><img src="{{ match.challengee.userprofile.avatar }}" /></td>
    <td><a href="{% url 'user:profile' match.challengee.username %}">{{ match.challengee.userprofile.handle }}</a></td>
    <td><a href="{% url 'ladder:detail' match.ladder.slug %}">{{ match.ladder }}</a></td>
    <td><img src="{{ match.winner.userprofile.avatar }}" /></td>
</tr>
{% endif %}
{% endfor %}
</table>
{% endblock content %}

ladder/templates/match_details.html
{% extends "layout.html" %}

{% load static %}
{% load humanize %}

{% block head %}{% endblock head %}

{% block content %}
<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

<h1>{{ match.challenger.userprofile.handle }} vs. {{ match.challengee.userprofile.handle }}</h1>

<div class="match_block" id="match_details">
    <table>
        <tr><td>Status:</td><td><strong>{{ match.related_challenge.get_accepted_display }}</strong></td></tr>
        {% if match.winner %}<tr><td>Winner:</td><td><a href="{% url 'user:profile' match.winner.username %}">{{ match.winner.userprofile.handle }}</a> [{{ match.winner_rank }}{{ match.get_winner_rank_icon_display }}]</td></tr>{% endif %}
        <tr><td>Started:</td><td>{{ match.date_challenged }} ({{ match.date_challenged|naturaltime }})</td></tr>
        <tr><td>Finished:</td><td>{{ match.date_complete }} ({{ match.date_complete|naturaltime }})</td></tr>
        <tr><td>Ladder:</td><td><a href="{% url 'ladder:detail' match.ladder.slug %}">{{ match.ladder }}</a></td></tr>
    </table>
</div>

<div class="match_block" id="match_participants">
    <table style="display:inline-block;">
        <tr><th colspan="2">Challenger</th></tr>
        <tr><td colspan="2"><img src="{{ match.challenger.userprofile.avatar }}"> <a href="{% url 'user:profile' match.challenger.username %}">{{ match.challenger.userprofile.handle }}</a></td></tr>
        <tr><td>Rank Before:</td><td>[{{ match.challenger_rank }}{{ match.get_challenger_rank_icon_display }}]</td></tr>
        <tr><td>Character:</td><td>{{ match.character1 }}</td></tr>
    </table>

    <table style="display:inline-block;">
        <tr><th colspan="2">Defender</th></tr>
        <tr><td colspan="2"><img src="{{ match.challengee.userprofile.avatar }}"> <a href="{% url 'user:profile' match.challengee.username %}">{{ match.challengee.userprofile.handle }}</a></td></tr>
        <tr><td>Rank Before:</td><td>[{{ match.challengee_rank }}{{ match.get_challengee_rank_icon_display }}]</td></tr>
        <tr><td>Character:</td><td>{{ match.character2 }}</td></tr>
    </table>
</div>

<div id="back_block">
    <a href="{% url 'ladder:match_list' match.ladder.slug %}">&lt;&lt; Back to {{ match.ladder.name }} - Match History</a>
</div>
{% endblock content %}

ladder/templates/match_list.html
{% extends "layout.html" %}

{% load static %}
{% load humanize %}

{% block head %}{% endblock head %}

{% block content %}
<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

<h1>{{ ladder.name }} - Match History</h1>

<div id="match_list">
    {% if matches %}
    <table>
    <tr>
        <th>Date</th>
        <th colspan="2">Challenger</th>
        <th></th>
        <th colspan="2">Defender</th>
        <th>Winner</th>
        <th></th>
    </tr>
    {% for match in matches %}
        {% if match.winner %}
        <tr>
            <td>{{ match.date_complete }}</td>
            <td><img src="{{ match.challenger.userprofile.avatar }}" /></td>
            <td><a href="{% url 'user:profile' match.challenger.username %}">{{ match.challenger.userprofile.handle }}</a>{% if match.challenger_rank %} [{{ match.challenger_rank }}{{ match.get_challenger_rank_icon_display }}]{% endif %}</td>
            <td><strong>vs</strong></td>
            <td><img src="{{ match.challengee.userprofile.avatar }}" /></td>
            <td><a href="{% url 'user:profile' match.challengee.username %}">{{ match.challengee.userprofile.handle }}</a>{% if match.challengee_rank %} [{{ match.challengee_rank }}{{ match.get_challengee_rank_icon_display }}]{% endif %}</td>
            <td><img src="{{ match.winner.userprofile.avatar }}" /></td>
            <td><em><a href="{% url 'user:profile' match.winner.username %}">{{ match.winner.userprofile.handle }}</a></em>{% if match.winner_rank %} [{{ match.winner_rank }}{{ match.get_winner_rank_icon_display }}]{% endif %}</td>
            <td><a href="{% url 'ladder:match_detail' ladder.slug match.id %}">Details</a>
        </tr>
        {% endif %}
    {% endfor %}
    </table>
    {% else %}
    <p>No matches have been recorded for this ladder.</p><br/>
    <p>Matches will appear when players challenge each other.</p>
    {% endif %}
</div>


<div id="back_block">
    <a href="{% url 'ladder:detail' ladder.slug %}">&lt;&lt; Back to {{ ladder.name }} rankings</a>
</div>
{% endblock content %}

ladder/templates/single_ladder_listing.html
{% extends "layout.html" %}

{% load static %}

{% block head %}{% endblock head %}

{% block content %}
{% load humanize %}

<h1>{{ ladder.name }}</h1>
<h4><em>{{ ladder.game.name }}</em></h4>
{% if ladder.max_players > 0 %}<p>Max players: {{ ladder.max_players }}</p>{% endif %}
<p>{{ ladder.description }}</p>
{% if user.is_authenticated %}
    {% if user == ladder.owner %}
    <ul>
        <li><a href="{% url 'ladder:update_ladder' ladder.slug %}">Edit/Update Ladder</a></li>
    </ul>
    {% endif %}
{% endif %}
<br>
{% if user.is_authenticated %}
{% if ladder.signups %}
    {% if join_link %}<a href="{% url 'ladder:join' ladder.slug %}">Join this Ladder!</a>{% endif %}
{% else %}
    <em>Signups for this ladder are currently closed.</em>
{% endif %}
{% if leave_link %}<a href="{% url 'ladder:leave' ladder.slug %}">Leave this Ladder!</a>{% endif %}
{% endif %}
<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% if rank_list %}
{% if not join_link and current_player_rank %}<p>Your current rank on the ladder is: {{ current_player_rank.rank|ordinal }}</p>{% endif %}
<hr>
<h2>Current Ranks</h2>
<table>
    <tr>
        <td colspan="2"></td>
        <th>Player</th>
    </tr>
    {% for player_rank, player_busy in rank_list %}   
        <tr>
            <td>{{ player_rank.rank|ordinal }}</td>
            <td>{% if player_rank.rank != 1 %}{{ player_rank.get_arrow_display }}{% endif %}</td>
            <td><span class="rank{{ player_rank.rank|ordinal }}"><img src="{{ player_rank.player.userprofile.avatar }}" /> <a href="{% url 'user:profile' player_rank.player.username %}">{{ player_rank.player.userprofile.handle }}</a></span></td>
            <td>
                {% if player_rank.rank in challengables %}
                <form action="{% url 'ladder:issue_challenge' ladder.slug %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="challenger" value="{{ user.pk }}" />
                <input type="hidden" name="challengee" value="{{ player_rank.player.pk }}" />
                <input type="hidden" name="ladder" value="{{ ladder.slug }}" />
                <input type="submit" value="CHALLENGE" {% if can_challenge or player_busy %}disabled="disabled"{% endif %} />
                </form>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>
{% endif %}
{% if open_challenges %}
<hr>
<h2>Open Challenges</h2>
<ul>
    {% for challenge in open_challenges %}
    <li><img src="{{ challenge.challenger.userprofile.avatar }}" />{% if challenge.challenger_rank %} [{{ challenge.challenger_rank }}{{ challenge.get_challenger_rank_icon_display }}]{% endif %}vs <img src="{{ challenge.challengee.userprofile.avatar }}" />{% if challenge.challengee_rank %} [{{ challenge.challengee_rank }}{{ challenge.get_challengee_rank_icon_display }}]{% endif %}{% if challenge.deadline %} Expires: <em>{{ challenge.deadline|naturaltime }}</em>{% endif %}</li>
    {% endfor %}
</ul>
{% endif %}
<hr>
<h2>Recent Matches:</h2>
<table>
<tr>
    <th>Date</th>
    <th colspan="2">Challenger</th>
    <td></td>
    <th colspan="2">Defender</th>
    <th colspan="2">Winner</th>
</tr>
{% for match in match_list %}
{% if match.winner %}
<tr>
    <td><a href="{% url 'ladder:match_detail' match.ladder.slug match.id %}">{{ match.date_complete|naturaltime }}</a></td>
    <td><img src="{{ match.challenger.userprofile.avatar }}" /></td>
    <td><a href="{% url 'user:profile' match.challenger.username %}">{{ match.challenger.userprofile.handle }}</a>{% if match.challenger_rank %} [{{ match.challenger_rank }}{{ match.get_challenger_rank_icon_display }}]{% endif %}</td>
    <td><strong>vs</strong></td>
    <td><img src="{{ match.challengee.userprofile.avatar }}" /></td>
    <td><a href="{% url 'user:profile' match.challengee.username %}">{{ match.challengee.userprofile.handle }}</a>{% if match.challengee_rank %} [{{ match.challengee_rank }}{{ match.get_challengee_rank_icon_display }}]{% endif %}</td>
    <td><img src="{{ match.winner.userprofile.avatar }}" /></td>
    <td><em><a href="{% url 'user:profile' match.winner.username %}">{{ match.winner.userprofile.handle }}</a></em>{% if match.winner_rank %} [{{ match.winner_rank }}{{ match.get_winner_rank_icon_display }}]{% endif %}</td>
</tr>
{% endif %}
{% endfor %}
</table><br />

{% endblock content %}

ladder/templates/update_ladder.html
{% extends "layout.html" %}

{% load static %}
{% block head %}{% endblock head %}


{% block content %}
<ul class="message">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
<h1>{{ ladder.name }}</h1>
<h4><em>{{ ladder.game.name }}</em></h4>
<br />
<form action="{% url 'ladder:update_ladder' ladder.slug  %}" method="post">
    {% csrf_token %}
    {{ form }}
    <br />
    <input type="submit" value="Submit" /> <a href="{% url 'ladder:detail' ladder.slug %}">cancel edits</a>
</form>
{% endblock content %}