elo/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
import ladder.views
import elo.views
from django.urls import include, path

app_name = 'elo'
urlpatterns = [
    url(r'^$',          ladder.views.index,                             name='index'),
    url(r'^l/',         include(('ladder.urls', 'ladder'),              namespace = 'ladder')),
    url(r'^u/',         include(('usercontrol.urls', 'usercontrol'),    namespace = 'user')),
    url(r'^logout/$',   elo.views.logout_view,                          name='logout'),
    url(r'^admin/',     admin.site.urls,                                name='admin'),
]

usercontrol/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import usercontrol.views

admin.autodiscover()

urlpatterns = [
    url(r'^profile/(?P<username>[-\w]+)$', usercontrol.views.profile,             name = 'profile'),
    url(r'^profile/(?P<username>[-\w]+)/matches$', usercontrol.views.match_list,  name = 'match_list'),
    url(r'^messages/$',                     usercontrol.views.message_list,       name = 'message_list'),
    url(r'^messages/challenges/$',          usercontrol.views.message_challenges, name = 'message_challenges'),
    url(r'^messages/matches/$',             usercontrol.views.message_matches,    name = 'message_matches'),
    url(r'^messages/(?P<message>\d+)/$',    usercontrol.views.message_detail),
    url(r'^messages/send$',                 usercontrol.views.message_send),
]

elo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User, blank=False, null=False, on_delete=models.CASCADE)

    # This will update their steam information every time they log in or something I guess yeah that sounds good.
    handle = models.CharField(max_length=50, blank=True)
    steamid = models.CharField(max_length=50, blank=True)
    url = models.CharField(max_length=255, blank=True)
    avatar = models.CharField(max_length=255, blank=True)
    avatarM = models.CharField(max_length=255, blank=True)
    avatarL = models.CharField(max_length=255, blank=True)
    primarygroup = models.CharField(max_length=50, blank=True)
    realname = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.handle

def create_user_profile(sender, instance, created, **kw):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

elo/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext

from itertools import chain

from django.urls.base import reverse

from ladder.models import Game, Match, Rank, Ladder, Challenge

def index(request):

    game_list = Game.objects.all()

    match_list = Match.objects.all().order_by('-date_complete')

    rank_list = Rank.objects.all()

    ladder_list = Ladder.objects.all()

    try:
        challenger_list = Challenge.objects.filter(match__challenger = request.user, accepted=False)
    except Exception:
        challenger_list = []
    try:
        challengee_list = Challenge.objects.filter(match__challengee = request.user, accepted=False)
    except Exception:
        challengee_list = []

    your_challenges = list(chain(challenger_list, challengee_list))

    return render(request, 'home.html', {'game_list':game_list, 'match_list':match_list, 'rank_list':rank_list, 'ladder_list':ladder_list, 'your_challenges':your_challenges}, context_instance=RequestContext(request))

def logout_view(request):
    logout(request)
    messages.success(request, "You have been signed out!")
    return HttpResponseRedirect(reverse('index'))

elo/templates/home.html
{% extends "layout.html" %}

{% load staticfiles %}
{% load humanize %}

{% block head %}{% endblock head %}


{% block content %}

<h2>Ladders:</h2>
<ul>
{% for ladder in ladder_list %}
<li><a href="{{ ladder.get_absolute_url }}">{{ ladder }}</a> ({{ ladder.game.abv }})</li>
{% endfor %}
</ul>

{% if your_challenges %}
<hr>
<h2>Your Challenges</h2>
<ul>
    {% for challenge in your_challenges %}
    <li>{{ challenge }}</li>  
    {% endfor %}
</ul>
{% endif %}

<hr>
<h2>Recent Matches:</h2>
<table>
<tr>
    <th>Date</th>
    <th colspan="2">Challenger</th>
    <td></td>
    <th colspan="2">Defender</th>
    <th>Ladder</th>
    <th>Winner</th>
</tr>
{% for match in match_list %}
{% if match.winner %}
<tr>
    <td>{{ match.date_complete|naturaltime }}</td>
    <td><img src="{{ match.challenger.get_profile.avatar }}" /></td>
    <td>{{ match.challenger.get_profile.handle }}</td>
    <td><strong>vs</strong></td>
    <td><img src="{{ match.challengee.get_profile.avatar }}" /></td>
    <td>{{ match.challengee.get_profile.handle }}</td>
    <td>{{ match.ladder.name }}</td>
    <td><img src="{{ match.winner.get_profile.avatarM }}" /></td>
</tr>
{% endif %}
{% endfor %}
</table>
{% endblock content %}

elo/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon"/>
        <link rel="stylesheet" href="{% static "css/reset.css" %}" />
        <link rel="stylesheet" href="{% static "css/layout.css" %}" />
        <link rel="stylesheet" href="{% static "css/tags.css" %}" />
        {% block head%}{% endblock head %}

        <title>ELO, World!</title>
    </head>

    <body>
        <div id="topper">
            <span class="title"><a href="{% url 'index' %}">ELO</a> - Electronic Ladder Organizer</span>
            {% if user.is_authenticated %}<p>Logged in as: <a href="{% url 'user:profile' user.userprofile.handle %}">{{ user.userprofile.handle }}</a> (<a href="{% url 'user:message_list' %}">messages</a> | <a href="{% url 'logout' %}">logout</a>){% else %}<a href="">Log In</a>{% endif %}
        </div>


        <div id="content">
            {% block content %}{% endblock content %}
        </div><!-- content -->


        <div id="footer">
            <a href="https://github.com/GordonsBeard/elo" title="Github Code">Github Repo</a>{% if user.is_staff %} + <a href="{% url 'admin:index' %}">Admin Site</a>{% endif %}
        </div><!-- footer -->
    </body>
</html>